# uv project file
[project]
name = "weatherclock"
version = "0.1.0"
description = "Add your description here"
requires-python = "~=3.12.0"
dependencies = [
    "flask",
    "python-dotenv",
    "requests"
]