# uv project file
[project]
name = "weatherclock"
version = "1.1.0"
description = "Weather Clock is a Flask web application that displays the current weather and time."
requires-python = "~=3.12.0"
dependencies = [
    "flask",
    "python-dotenv",
    "requests"
]